spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/big_event
    username: root
    password: 123456
  data:
    redis:
      host: localhost
      port: 6379

mybatis:
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名和下划线命名的转换

alipay:
    easy:
      protocol: https
      gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do
      gatewayHost: openapi-sandbox.dl.alipaydev.com
      signType: RSA2
      appId: 9021000146602975
      merchantPrivateKey: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCVdza1IwS8wzceWb+l7pNwhQxg3IrB19nIhCfeWftx5ICUkGDpvvmNpRTYOM8uJJ1nMAyiB8+nyylArup2AIz/UdJatHOBITZNzmG9FFPd+QddAKeDgshVtX34JtEl5R3kytOl7bn6cYfK/s5djaGviQekIjkkz8qNQQRc+WBZwFNrwPkJdgVSrsMjx1o321RBeiylPWX/YJP+sUR3MFPwsfT9i+wMmYbvrscy/KDmscidVyB2EJxUpeYU8GbzgEdvVQTFTWeHBsr2CWp/nIgUAaODz5L2d82M4NOT0s3QoQ7lmvakGr+68rR4yvL7gjth4sdMgVcktAfG4J2Cny0NAgMBAAECggEAIQYGAF+MXGiFdR8/SNo9mU7MPVp9DfczFyqb5HTdKXzjK+/6earIWJNw15U1sWxFmtby85nmN5ybsL707r2QaZkacRANtSoxZV+EGNK09QZgqhvK5zOuL8G542owK79Dq5lkyfSMctlCt4c08Vapsq8EES++kHOYvTzwSdqPf0S4P+QKNfMXnHWTRpEm06mfebCkWZq7sJ2QUdAyiEEvwPcnHPq2uidbnbCL8TBBGSE2g7LET2tELOdaOxKH3YbSDnCzx+qOX421loxrIyIh/QmoDhfcAPfwhyS+gmNXu6sSIFkObIRVvV4OviLmMFl0bzbNnXqPsxLgCPfaGpSIAQKBgQDZNlh1r857emEZ+buKPC6qUkZFcT/bcNCet2uKK8Rczbg8Jabse2R8iGYhRDFjHqtlwQ0B08ldMc6xumPk0xFI/r8l+XoTzP+xkFN30v7K3EbqdJy9bljc4GAqlZEdybK+eVjwMOyvmgY5JodxWNHeNMsaEzGECLiK7qpawF3jYQKBgQCwJ+VdRMUAF//gHBtqoSWtjZwI93jHvVsLWn+jzFiWo4+AeoOf3r+L3rlYHK/DIaehSeFQqexhgIz3NdUnmzlBYz3biD+OYrBy/iTN6KIsry3DGxSryxePGVDBMbTruxJHK0hFJjCRp4EPDF10SHVxG1sOdNp7deP0SlpqCP9VLQKBgA3CAnJZ01NA2huiFL3Zt/7zvR2y4Z+Nkrkq1vXmdcaHBS9SFzONUT0OCqH6xsIHdEW6p49BEdUETZo2OxOIRuT/ta27En9kkaF2icLiK18/+oHpJvBcp+Y9k/m+hXWEi/zChN6ZyrQIpnJCPXvxa0GOyHp7UryRLNcn7MRYwNmhAoGAWHjBHpXSZ1imX1Veg7BJrx/HNU2tMIwutMYQAyE3gPjGst1VTC7gfwwuhE1sDRHTEhN8ATpGiTW6FtLHqmuwVuHUCHUmjomMW0S/EVd8U/rrfekU+a83ttwdDdq8JgS/ilT3qBslG5JIJFmueh+GNHdrxRf1PzqXcXMCc+zu6EUCgYAqcG9BNivpt2IT6ulA34ke+la44FzT8bFyuaipLN6B6OA+qDMSDWI4LtTHfXGpJz/2n3X7dCvhDsUxB/rKkNY2U95HN0BzWQ71mfxaiW7Xr0xWcb746JMcNQQh6GL6BvxLw3JZbY1iLakkq6XyvOk9cp8M07E7d+nOUAB0ERPlzQ==
      alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoeXYnMYURNRmC/dUSVsuKJlZEZh1ncBD+RhJtBp5k+3+H5cVTnoth9Z97Vuhh5QRo3jJg3ShSxj8TON4KBZ5H7bnda6+8FSGh3soiS49Rd0DcJ3DO84/xyDkLIkmw4v+LVshM2+BYeER2bDuXzwaijK0/YrewpwNDmPWki7c8DDBZ1WsNfkcO+JnW54Z68TU8jRgD/FYT+beLsLx2MN+uJiCZ0zQIAJL30nNMxrmCsg7YHJtn+gEL9Mpd2f/qerb88piTki976aAarcgFbh0jHS87bftpQiPkZBkLOchP45CntK9WfsigNk4HrSXJ1ozgWOkdRdEHnJJSSrrNXEwswIDAQAB
      notifyUrl: https://2263c31f.r25.cpolar.top/notify